import React, { useState, useEffect } from 'react';
import { reportAPI } from '../services/api';
import { FileText, Download, Printer, Eye, Calendar, Plus, RefreshCw, X } from 'lucide-react';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  // Form State
  const [reportTitle, setReportTitle] = useState('');
  const [reportType, setReportType] = useState('Financial Summary Report');
  const [format, setFormat] = useState('PDF');
  const [startDate, setStartDate] = useState('2026-01-01');
  const [endDate, setEndDate] = useState('2026-06-30');

  // Preview State
  const [previewReport, setPreviewReport] = useState(null);

  const reportTypes = [
    'Fuel Report',
    'Expense Report',
    'Operational Cost Report',
    'Maintenance Cost Report',
    'Profitability Report',
    'ROI Report',
    'Financial Summary Report'
  ];

  const fetchReportsList = async () => {
    try {
      setLoading(true);
      const { data } = await reportAPI.getReports();
      setReports(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReportsList();
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    try {
      setGenerating(true);
      const title = reportTitle || `Quarterly ${reportType} (${startDate} to ${endDate})`;
      
      const payload = {
        title,
        type: reportType,
        format,
        filtersUsed: { startDate, endDate }
      };

      await reportAPI.createReport(payload);
      setReportTitle('');
      fetchReportsList();
    } catch (err) {
      console.error(err);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = async (id, title, fileFormat) => {
    try {
      const response = await reportAPI.downloadReport(id);
      // Create element link to trigger local download
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      const extension = fileFormat.toLowerCase() === 'excel' ? 'xlsx' : fileFormat.toLowerCase();
      link.setAttribute('download', `${title.replace(/\s+/g, '_')}_REP.${extension}`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      console.error('Error downloading report file', err);
    }
  };

  const handlePrint = (report) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>${report.title}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #333; }
            h1 { border-bottom: 2px solid #ccc; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
            th { background-color: #f5f5f5; }
          </style>
        </head>
        <body>
          <h1>TransitOps ${report.type}</h1>
          <p><strong>Report ID:</strong> ${report.reportId}</p>
          <p><strong>Generated By:</strong> ${report.generatedBy}</p>
          <p><strong>Date:</strong> ${new Date(report.dateGenerated).toLocaleString()}</p>
          <hr/>
          <h3>Aggregated Summary Calculations</h3>
          <table>
            <tr><th>Metric</th><th>Calculation Value</th></tr>
            <tr><td>Total Fleet Operational Cost</td><td>$342,500.00</td></tr>
            <tr><td>Total Revenue Generated</td><td>$580,000.00</td></tr>
            <tr><td>Net Fleet Profit</td><td>$237,500.00</td></tr>
            <tr><td>ROI Yield Average</td><td>18.4%</td></tr>
          </table>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="space-y-6">
      
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold text-white tracking-tight">Financial Reports Generator</h2>
          <p className="text-xs text-gray-500">Create, compile, and download formal fleet audits</p>
        </div>
        <button onClick={fetchReportsList} className="p-2 bg-white/5 border border-darkBorder hover:text-white rounded-xl transition-all">
          <RefreshCw size={16} />
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* GENERATOR FORM PANEL */}
        <div className="glass-panel p-6 rounded-2xl border border-darkBorder lg:col-span-1 h-fit">
          <h3 className="text-sm font-bold text-white mb-4">Generate Report</h3>
          
          <form onSubmit={handleGenerate} className="space-y-4">
            <div>
              <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">Report Template</label>
              <select
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
                className="w-full bg-darkBg border border-darkBorder rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-accentCyan"
              >
                {reportTypes.map(t => <option key={t} value={t}>{t}</option>)}
              </select>
            </div>

            <div>
              <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">Custom Title (Optional)</label>
              <input
                type="text"
                value={reportTitle}
                onChange={(e) => setReportTitle(e.target.value)}
                placeholder="Q2 Operational Costs Sheet"
                className="w-full bg-darkBg border border-darkBorder rounded-xl px-3 py-2 text-xs text-white placeholder-gray-600 focus:outline-none focus:border-accentCyan"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">Start Date</label>
                <input
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  className="w-full bg-darkBg border border-darkBorder rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-accentCyan"
                />
              </div>
              <div>
                <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">End Date</label>
                <input
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  className="w-full bg-darkBg border border-darkBorder rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-accentCyan"
                />
              </div>
            </div>

            <div>
              <label className="block text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-1">Preferred Export Format</label>
              <select
                value={format}
                onChange={(e) => setFormat(e.target.value)}
                className="w-full bg-darkBg border border-darkBorder rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-accentCyan"
              >
                <option value="PDF">Standard PDF document</option>
                <option value="CSV">Comma Separated Values (CSV)</option>
                <option value="EXCEL">Microsoft Excel Sheet (XLSX)</option>
              </select>
            </div>

            <button
              type="submit"
              disabled={generating}
              className="w-full bg-gradient-to-r from-accentCyan to-accentGreen text-darkBg font-bold py-2.5 px-4 rounded-xl hover:shadow-glow transition-all duration-300 disabled:opacity-50 text-xs"
            >
              {generating ? 'Processing Data...' : 'Compile & Export'}
            </button>
          </form>
        </div>

        {/* LOGGED REPORTS LIST */}
        <div className="glass-panel p-6 rounded-2xl border border-darkBorder lg:col-span-2">
          <h3 className="text-sm font-bold text-white mb-4">Historical Audit Trails</h3>
          
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-darkBorder text-gray-400 uppercase font-semibold bg-white/5">
                  <th className="py-2.5 px-3">Report ID</th>
                  <th className="py-2.5 px-3">Title / Template</th>
                  <th className="py-2.5 px-3">Format</th>
                  <th className="py-2.5 px-3">Date Generated</th>
                  <th className="py-2.5 px-3 text-center">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5 text-gray-300">
                {loading ? (
                  <tr>
                    <td colSpan="5" className="text-center py-6 text-xs text-gray-500">
                      Loading generated logs...
                    </td>
                  </tr>
                ) : reports.length === 0 ? (
                  <tr>
                    <td colSpan="5" className="text-center py-6 text-xs text-gray-500">
                      No reports generated yet.
                    </td>
                  </tr>
                ) : (
                  reports.map((rep) => (
                    <tr key={rep._id} className="hover:bg-white/5 transition-colors">
                      <td className="py-3 px-3 font-mono font-bold text-gray-200">{rep.reportId}</td>
                      <td className="py-3 px-3">
                        <div className="font-semibold text-white">{rep.title}</div>
                        <div className="text-[10px] text-gray-500">{rep.type}</div>
                      </td>
                      <td className="py-3 px-3">
                        <span className="px-1.5 py-0.5 rounded bg-white/5 border border-white/5 text-[10px] font-bold text-accentCyan">
                          {rep.format}
                        </span>
                      </td>
                      <td className="py-3 px-3 text-gray-400">
                        {new Date(rep.dateGenerated).toLocaleString()}
                      </td>
                      <td className="py-3 px-3 flex items-center justify-center space-x-1.5">
                        <button
                          onClick={() => setPreviewReport(rep)}
                          className="p-1 text-gray-400 hover:text-white bg-white/5 rounded border border-darkBorder"
                          title="Preview"
                        >
                          <Eye size={12} />
                        </button>
                        <button
                          onClick={() => handleDownload(rep._id, rep.title, rep.format)}
                          className="p-1 text-gray-400 hover:text-accentGreen bg-white/5 rounded border border-darkBorder"
                          title="Download"
                        >
                          <Download size={12} />
                        </button>
                        <button
                          onClick={() => handlePrint(rep)}
                          className="p-1 text-gray-400 hover:text-accentCyan bg-white/5 rounded border border-darkBorder"
                          title="Print"
                        >
                          <Printer size={12} />
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

      </div>

      {/* PREVIEW DIALOG MODAL */}
      {previewReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="w-full max-w-2xl glass-panel p-6 rounded-2xl border border-darkBorder relative shadow-2xl animate-scaleIn">
            <button
              onClick={() => setPreviewReport(null)}
              className="absolute right-4 top-4 text-gray-400 hover:text-white"
            >
              <X size={18} />
            </button>

            <h3 className="text-base font-bold text-white mb-2">
              Report Preview: {previewReport.title}
            </h3>
            <p className="text-xs text-gray-500 mb-6 uppercase tracking-wider">
              Template: {previewReport.type} | Format: {previewReport.format}
            </p>

            <div className="bg-darkBg p-6 rounded-xl border border-darkBorder text-xs text-gray-300 font-mono space-y-4 max-h-96 overflow-y-auto">
              <div className="border-b border-white/5 pb-3">
                <div>TRANSITOPS FLEET OPERATIONS ERP</div>
                <div>GENERATED BY: {previewReport.generatedBy}</div>
                <div>DATE GENERATED: {new Date(previewReport.dateGenerated).toLocaleString()}</div>
              </div>

              <div>
                <p className="text-white font-bold mb-2">1. EXECUTIVE OVERVIEW METRICS</p>
                <div className="grid grid-cols-2 gap-2 text-[11px] bg-white/5 p-3 rounded-lg">
                  <div>Total Fuel Costs: $148,250.00</div>
                  <div>Total Maintenance Costs: $84,900.00</div>
                  <div>Miscellaneous Bills: $109,350.00</div>
                  <div>Total Operational Cost: $342,500.00</div>
                  <div>Simulated Fleet Revenue: $580,000.00</div>
                  <div>Net Profit: $237,500.00</div>
                  <div>Fleet ROI Yield: 18.4%</div>
                  <div>Profit Margin: 40.9%</div>
                </div>
              </div>

              <div>
                <p className="text-white font-bold mb-2">2. AUDITED CONSTRAINTS & ALERTS</p>
                <ul className="list-disc list-inside space-y-1 text-gray-400">
                  <li>Fuel Budget exceeded by 12% in the South region.</li>
                  <li>Truck-08 achieved maximum ROI at 24.2%.</li>
                  <li>Maintenance costs decreased by 8.2% through scheduled intervals.</li>
                </ul>
              </div>
            </div>

            <div className="pt-6 mt-6 border-t border-darkBorder flex justify-end space-x-2">
              <button
                onClick={() => handlePrint(previewReport)}
                className="px-4 py-2 border border-darkBorder rounded-xl hover:bg-white/5 text-xs font-semibold flex items-center space-x-1.5"
              >
                <Printer size={12} /> <span>Print</span>
              </button>
              <button
                onClick={() => handleDownload(previewReport._id, previewReport.title, previewReport.format)}
                className="px-4 py-2 bg-gradient-to-r from-accentCyan to-accentGreen text-darkBg rounded-xl hover:shadow-glow text-xs font-bold flex items-center space-x-1.5"
              >
                <Download size={12} /> <span>Download {previewReport.format}</span>
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default Reports;
