@echo off
echo Stopping old node processes...
taskkill /F /IM node.exe >nul 2>&1

echo Starting Financial Analyst Frontend...
start cmd /k "cd Financial_Analyst\client && npm run dev"
echo Starting Financial Analyst Backend...
start cmd /k "cd Financial_Analyst\server && node server.js"

echo Starting Dispatcher Frontend...
start cmd /k "cd dispatcher\frontend && npm run dev"
echo Starting Dispatcher Backend...
start cmd /k "cd dispatcher\backend && node server.js"

echo Starting Safety Officer Frontend...
start cmd /k "cd safety_officer\frontend && npm run dev"
echo Starting Safety Officer Backend...
start cmd /k "cd safety_officer\backend && node server.js"

echo Starting Fleet Manager Frontend...
start cmd /k "cd ""Fleet Manager\frontend"" && npm run dev"
echo Starting Fleet Manager Backend...
start cmd /k "cd ""Fleet Manager\backend"" && npm run dev"

echo All services started!
echo Starting Login Portal...
start cmd /k "npx -y serve portal -l 8080"
