import Report from '../models/Report.js';
import FuelLog from '../models/FuelLog.js';
import Expense from '../models/Expense.js';

// @desc    Get all generated reports list
// @route   GET /api/reports
// @access  Private
export const getReports = async (req, res) => {
  try {
    const reports = await Report.find({}).sort({ dateGenerated: -1 });
    res.json(reports);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Create / Generate a report log
// @route   POST /api/reports
// @access  Private
export const createReportLog = async (req, res) => {
  try {
    const { title, type, format, filtersUsed } = req.body;

    const count = await Report.countDocuments();
    const reportId = `REP-${String(count + 1).padStart(4, '0')}`;

    const report = new Report({
      reportId,
      title,
      type,
      format,
      generatedBy: req.user?.username || 'Financial Analyst',
      filtersUsed: filtersUsed || {}
    });

    const createdReport = await report.save();
    res.status(201).json(createdReport);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
};

// @desc    Simulate/Download reports
// @route   GET /api/reports/:id/download
// @access  Private
export const downloadReportFile = async (req, res) => {
  try {
    const report = await Report.findById(req.params.id);
    if (!report) {
      return res.status(404).json({ message: 'Report not found' });
    }

    // Set mock report payload to download
    const isCsv = report.format === 'CSV';
    const isExcel = report.format === 'EXCEL';

    if (isCsv || isExcel) {
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename=${report.title.replace(/\s+/g, '_')}_${report.reportId}.${isCsv ? 'csv' : 'xlsx'}`);

      // Render CSV header and basic rows
      let csvContent = `Report ID,Title,Type,Generated By,Date Generated,Format\n`;
      csvContent += `${report.reportId},"${report.title}","${report.type}","${report.generatedBy}","${report.dateGenerated}","${report.format}"\n\n`;
      csvContent += `Data Summary,Metric,Value\n`;
      csvContent += `,Total Fleet Operational Cost,$342500\n`;
      csvContent += `,Total Revenue Generated,$580000\n`;
      csvContent += `,Net Fleet Profit,$237500\n`;
      csvContent += `,ROI Average,18.4%\n`;

      return res.send(csvContent);
    } else {
      // PDF
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=${report.title.replace(/\s+/g, '_')}_${report.reportId}.pdf`);
      // Just send a mock PDF file text block or header
      return res.send(`%PDF-1.4\n%mock pdf file content for TransitOps Dashboard\n/Title (${report.title})\n/Author (${report.generatedBy})`);
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
